### ISSUE TITLE
license(s)?

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-website#1]

**Comment by jbpoline** [comment]
CC0 ?

**Comment by yarikoptic** [comment]
for a website it might be well be something like CC BY,... but also it uses other libraries etc so altogether might be bound quite a bit more -- I didn't inspect

**Comment by yarikoptic** [comment]
So what is the verdict @chrisfilo and @jbpoline ?

**Comment by sappelhoff** [comment]
I think the website should share a LICENSE with the specification ([cc-by](https://github.com/bids-standard/bids-specification/blob/master/LICENSE)).

> but also it uses other libraries etc so altogether might be bound quite a bit more -- I didn't inspect

I am obviously not a lawyer, but I guess we can just add the cc-by license despite the fact that we are using tools that are licensed themselves (circleci, jekyll, ...). At least this is what every large library hosted on GitHub does ... they have a license for their code and work ... and don't mention the other things that are included,

Am I wrong @yarikoptic?
