### ISSUE TITLE
BEP 003 link is out-of-date

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-website#100]
Currently links to outdated Google Doc. Should point to PR and/or rendered draft.

Can probably do this tomorrow if nobody is feeling itchy and needs something to do. :-)

Related to #96.

**Comment by sappelhoff** [comment]
I think both the branch and the rendered draft can be confusing for newcomers. I suggest to keep the link to the Gdoc, but add a brief and very obvious disclaimer at the beginning of the Gdoc, linking to a) the branch, and b) the rendered draft

**Comment by effigies** [comment]
I updated the top with the following text:

> This document has been converted into a pull request on the BIDS specification source repository. As further work is done, this document may become out of date. This should be treated as a historical reference.

Will still update the link on the website.
