### ISSUE TITLE
Add BEP numbers and links for NIRS and motion capture

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-website#120]
Both are now in a decent state for the community to work on, with a github issue and a google doc. See

- https://github.com/bids-standard/bids-specification/issues/438
- https://github.com/bids-standard/bids-specification/issues/443

@sappelhoff do you know whether a specific procedure applies, or do I just assign them a number and add them here to the website?

**Comment by sappelhoff** [comment]
done in #123
