### ISSUE TITLE
Update request of BIDS converter for preclinical MRI.

### ISSUE THREAD

**Issue by dvm-shlee** [bids-standard/bids-website#124]
Dear BIDS team,

First of all, thank you for this great data structure, I have been using this guideline to handle all the data, and have been developed several tools that utilizing BIDS and it is became amazingly efficient.

I'm opening this issue because I hope to ask adding my BIDS compatible converter for preclinical MRI (Bruker raw data).  If this is not the place to request this, please let me know, I will close this issue as soon as possible.

Briefly, my code is designed to help to convert multiple sets of raw data for the Bruker's preclinical scanner by creating an excel file and JSON file as a template to guide filename as well as metadata parsing with custom syntax. So I think this will be a useful tool for the animal MR imaging researcher who wants to adapt BIDS for their research. 

Here is my Github link : [BrkRaw](https://github.com/dvm-shlee/bruker)
And below content is what I posted at README.md regarding the BIDS.

#### Automatic BIDS organizer with template files
![brkraw bids](https://github.com/dvm-shlee/bruker/blob/master/imgs/brkraw_bids_conv.png?raw=true)
**The usage of the command-line tool 'brkraw' for BIDS data organization.**

- Upgraded feature to reduce the burden on renaming according to BIDS standard.
- Create a BIDS file table with excel format to use as a template for updating metadata that required to use for file naming.
- This command will also generate the BIDS_META_REF.json which allows you to set custom syntax to parse the metadata from the raw data. The default reference of the current version is based on BIDS 1.2.2.
- To learn more detail, please check our example 
[Jupyter Notebooks](https://github.com/dvm-shlee/bruker/blob/master/examples/BrkRaw_PythonAPI.ipynb).
```angular2html
$ brkraw bids_list <parent folder> <filname>.xlsx
```

- Build BIDS dataset according to the excel file generated with 'bids_list' command above.
```angular2html
$ brkraw bids_converter <parent folder> <BIDS table file.xlsx>

$ brkraw bids_converter <parent folder> <BIDS table file.xlsx> -r <BIDS meta reference file.json>
```

Again please let me know if I post this at the wrong place.
Thank you! and I hope you are all staying safe and healthy from COVID-19!

**Comment by sappelhoff** [comment]
Hi @dvm-shlee thanks for your detailed request and for developing a BIDS converter :-)

The tool looks well documented and useful at a first glance. I have no objections to include this in our list of converters.

I suggest you open a pull request to this bids-website repo, adding your converter to the list in this file: https://github.com/bids-standard/bids-website/blob/gh-pages/_pages/benefits.md

please use the same syntax as the other items in the converter list. Once you opened a PR, I will ask some other reviewers whethr they have objections --> and if they don't we can simply merge the PR.

---

PS: I noticed that all your commits in your repository are not linked to your GitHub account, your contributor count thus shows up as 0:

![image](https://user-images.githubusercontent.com/9084751/81493976-397d6600-92a5-11ea-988f-b9b79cc6d669.png)

to fix this, you may want to edit your `.gitconfig` file to have the same email as your GitHub account, see here for more information: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Comment by dvm-shlee** [comment]
@sappelhoff  Thank you, I think while I change my email in .gitconfig, I didn't update that email in my account. Thank you for letting me know and kind of explanation about the instruction.
I just open the pull request, and I will close this issue since I've got an answer I need. Thanks!
