### ISSUE TITLE
Light background color, bigger fontsize

### ISSUE THREAD

**Issue by guiomar** [bids-standard/bids-website#141]
Hi!

Is it possible to switch to light background colour and a bit bigger fontsize for the text?
I find it a bit hard to read. What do you think?

Thanks!

**Comment by franklin-feingold** [comment]
yep! I think this can be included when the website is enhanced to describe the organization

**Comment by hoechenberger** [comment]
@guiomar 
Have things improved for you? https://bids.neuroimaging.io
Or do you think there's still too much contrast?

**Comment by guiomar** [comment]
Thanks a lot @hoechenberger !! Fontsize looks very good to me now :)
I would also like to have some light background (light grey almost white), with dark (grey almost black) font colors. But maybe it's just my preference! If someone could show me how could I edit this things (or point to a tutorial) I can also start playing a bit, especially with the content.

**Comment by hoechenberger** [comment]
We could add day and night themes (i.e., bright and dark), and allow switching. I will see if I can find some time to look into this.

**Comment by guiomar** [comment]
I'm trying a general draft for the website here: 
https://sites.google.com/d/1UJoI93oi5IMJmhtqUL_jNXK9VRYhUelv/p/1JaTYkrEONIw2abobzRMi66YpCTX3xegu/edit

It's in google sites, as I don't really know how to use other tools for now. But at least it can give an idea :)

**Comment by hoechenberger** [comment]
Looks nice and super clean! I wonder if we should use Hugo with a nice theme.

**Comment by Remi-Gau** [comment]
Will close this one, since it seems that the new website will be mkdocs based
