### ISSUE TITLE
Redirect to starter kit?

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-website#171]
In light of discussion where starter kit might get overhauled, having a redirect might give us flexibility to move it in the future without breaking old versions of the spec.

We could use https://bids.neuroimaging.io/starter-kit

**Comment by robertoostenveld** [comment]
Agreed about the possibility for redirecting. 

In one of the steering group meetings we identified the "neuroimaging.io" domain as being suboptimal and have hence reserved "bids-standard.org" (which now redirects to the current domain). We might also consider planning already bit further ahead and start the conceptual move of the different "aspects" of the BIDS standard and ecosystem to bids-standard.org, i.e. the specific link could then be to <http://bids-standard.org/starter-kit>.

**Comment by sappelhoff** [comment]
> In one of the steering group meetings we identified the "neuroimaging.io" domain as being suboptimal and have hence reserved "bids-standard.org" (which now redirects to the current domain). 

great news! I remember being confused by bids.neuroimaging.io when I joined BIDS.
