### ISSUE TITLE
Run linkchecker regularly

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-website#187]
at least one link on https://bids.neuroimaging.io/governance.html is broken --> https://predictablynoisy.com/rust-governance

**Comment by Remi-Gau** [comment]
Easy option is a preset guthub action:

https://github.com/Remi-Gau/eCobidas/blob/master/.github/workflows/check_md_links.yml

**Comment by sappelhoff** [comment]
Thanks for the suggestion @Remi-Gau - I'll see if I can get it to work and fix some links.

**Comment by Remi-Gau** [comment]
Hmm...

It does detect some, but also gives some false positives.

**Comment by Remi-Gau** [comment]
https://github.com/bids-standard/bids-website/runs/2817770324

**Comment by sappelhoff** [comment]
yes, currently working on it :)

I'll open a PR so you can see
