### ISSUE TITLE
Suggest minor change to top level menus (related to issue #93)

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-website#200]
(related to #93 )

Here are some suggestions for minor changes to top level menus:

ABOUT
NEWS
BENEFITS
SPECIFICATION
GET STARTED
GET INVOLVED
SOFTWARE
GOVERNANCE
ACKNOWLEDGMENTS

- [x] Here THE SPECIFICATION becomes SPECIFICATION to make it shorter.
- [x] GETTING STARTED becomes GET STARTED to make shorter and parallel to GET INVOLVED.

- [ ] SOFTWARE (or maybe TOOLS?) is added because right now a list of SOFTWARE using BIDS is under the BENEFITS page which is not where I would look.  Having its own menu item promotes software and/or tools, which most BIDS users are going to be particularly interested in.

- [ ] Also, could the GET_INVOLVED page benefit from the addition of a brief statement about how to get tools listed or contributing BIDS apps?

**Comment by sappelhoff** [comment]
Thanks @VisLab I like your suggestions, and I think especially the first two ones could be implemented without a lot discussion (but all others who read this: let me know if you disagree). I opened #201 for that.

Regarding the remaining points:

- Software section
- Improving Get Involved

I agree with both your suggestions, but will leave implementation /  concrete text suggestions to others.

**Comment by Remi-Gau** [comment]
I agree with getting getting the tool lists out of BENEFITS. I also think that the page should be called SOFTWARES: although maybe less accurate technically than TOOLS, I think people will understand it better.

**Comment by robertoostenveld** [comment]
I like the proposed change. I am only worried whether such a long list of top-level menu items will show correctly, or whether it gets too wide. The only way to find that out is to try.

**Comment by Remi-Gau** [comment]
Tempted to actually have the content of the SPECIFICATION page moved into the GET STARTED one.

Other possibility: put their content into the header of the website so it is always accessible.

**Comment by Remi-Gau** [comment]
@VisLab I am going to close this one as we are now moving to a new website layout and navigation: https://bids-website.readthedocs.io/en/latest/

if you have time to give the new website a look and tell us ways we can improve, your feedback is always appreciated.
