### ISSUE TITLE
Point backwards-incompatible proposals toward `bids-2-devel` repo

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-website#205]
I noticed that the section on BIDS 2.0 proposals in `get_involved` still points to the frozen GDoc, instead of the [`bids-standard/bids-2-devel`](https://github.com/bids-standard/bids-2-devel) repo or, preferably, [its issues page](https://github.com/bids-standard/bids-2-devel/issues).

```markdown
Note that all of the extension ideas that are not backwards compatible and thus
will have to wait for BIDS 2.0 are listed
[here](https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw){:target="_blank"}.
```

**Comment by sappelhoff** [comment]
Thanks for noticing @tsalo, should be fixed now.
