### ISSUE TITLE
BEP listing on website is out of sync with the standard

### ISSUE THREAD

**Issue by nicholst** [bids-standard/bids-website#208]
Looking for info on BEPs, I noticed that the table on the website:

https://bids.neuroimaging.io/get_involved.html

is different than in the standard:

https://bids-specification.readthedocs.io/en/v1.2.1/06-extensions.html

I guess there are two issues, one is just the fixes to bring it up to date, and, second, a standing method to keep it up to date.  Not sure if it is feasible to isolate the MD table content in the standard and somehow source it into the website?

Not sure what's the best mechanism going forward.

**Comment by nicholst** [comment]
Ooops! Sorry!  I just saw that in the current Github (but not yet rendered) standard this is delt with:

https://github.com/bids-standard/bids-specification/blob/master/src/07-extensions.md

and the reader is referred to the website.

Sorry!

**Comment by sappelhoff** [comment]
okay, nevermind (simultaneous posting) :+1:

**Comment by nicholst** [comment]
Blame Google!  I searched for "bids derivatives contributors" and it took me to the old version :)
