### ISSUE TITLE
Improve rendering of tables on mobile

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#211]
This affects:
- converter tables
- BEP listing
- listing of maintainers and steering group
- others?

Example:

![Uploading Screenshot from 2021-11-02 08-17-48.png…]()

**Comment by sappelhoff** [comment]
I think you submitted this issue so quick that GitHub didn'T have time to upload your screenshot :-)

(happened to me many times already)

![image](https://user-images.githubusercontent.com/9084751/139826050-8587872d-6017-46a1-ae53-ed9bd5de1bb2.png)

**Comment by Remi-Gau** [comment]
oops. Is this the github equivalent of forgetting the attached document in an email?

![Screenshot from 2021-11-02 08-17-48](https://user-images.githubusercontent.com/6961185/139832883-d7448c1b-d125-4ceb-878c-f7470e8b6838.png)
