### ISSUE TITLE
Mark MIDS (BEP25) as withdrawn (rejected?)

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-website#236]
Following meeting with steering group, MIDS has been effectively withdrawn, as it is more a set of local conventions and not applicable to the community at large.

**Comment by sappelhoff** [comment]
How about we add two more subheadings:

- repurposed BEPs (this would be what is currently BEP015)
- withdrawn/rejected BEPs (with a column that lists the reason)

This way we don't have to strictly specify whether a BEP was rejected or withdrawn.

**Comment by yarikoptic** [comment]
would be nice to have more details... and also the BEP025 work document (if I googled it right - https://docs.google.com/document/d/1xeiFACAnK_X64kL6XoXo8vpZ9Bn6B5Xd3j59Le1clRE/edit#heading=h.4k1noo90gelw) doesn't mention that it is no more WiP.  Also if someone could extend " as it is more a set of local conventions and not applicable to the community at large." a little - would be appreciated.  One of the MIDS aspects was seems to add a few more data modalities (e.g. xray) which should have been totally fine/valid and generally applicable.

**Comment by sappelhoff** [comment]
@yarikoptic perhaps we could request a short statement from the BEP leads in this issue. I don't know their GitHub handles, so we could write an email -- do you want to write it, perhaps?

Regarding your point about aspects of the BEP being salvageable: It would be fine with me if somebody wants to either:

1. make a new BEP based on these isolated parts (xray?) and cite the previous BEP
1. completely revamp the present BEP025 and make it more narrow and mergeable again

I generally think option 1 would be cleaner. But in the case of option 2, nothing would prevent us to update the BEP table on the website and move BEP025 from the planned "withdrawn/rejected" category back to the "work in progress" category.

**Comment by yarikoptic** [comment]
> Following meeting with steering group, MIDS has been effectively withdrawn
> ...
>  I don't know their GitHub handles, so we could write an email -- do you want to write it, perhaps?

Could someone from steering group who interacted with someone from BEP25 leading to withdrawn contact that person?

**Comment by sappelhoff** [comment]
posting a part of the reply here for posterity:

> But we believe that after having tested this structure in several projects, for example:
> 
> Datasets in IEEE:
> 10.21227/w3aw-rv39
> 10.21227/m4j2-ap59
> 
> preprints and papers:
> arXiv:2111.08712 (To be published)
> arXiv:2006.05274 (To be published)
> NatureData: SDATA-22-00159 (Accepted but not yet visible)
> 
> I think it would be beneficial to include MIDS ideas within BIDS. We would like to evaluate with a bit more time how to offer these local conventions within BIDS but we need some more time to be able to dedicate to it. If possible, I would like to avoid repealing BEP025 for the time being.

**Comment by josator2** [comment]
Dear everyone,

First of all I am sorry I have not been updating the development of BEP025 due to the workload I was having this last year. Therefore, I am starting this work that include these ideas from BEP025 into BIDS.

To do so, I refer to the ideas described in this issue:

> 1. make a new BEP based on these isolated parts (xray?) and quote the previous BEP.
> 2. completely revamp the current BEP025 and make them narrower and mergable again.

I have thought about doing the first proposal where each usable part for BIDS is atomised into a new different BEP. I think that would be the best option to make all the concepts described clear. That said, I have a doubt about how to name each BEP. Could I name the extension label as BEP025.**N** where **N** is a numeric section or would I have to name it as the next available label (in this case bep037,bep038,...).

**Comment by robertoostenveld** [comment]
I prefer the principle to keep the BEP naming simple, as not to end up with a hypothetical `BEP025.2.a-rev3.rc1`. Simple numbering also aligns with the PEPs ([Python Extension Proposals](https://peps.python.org/pep-0001/)) which inspired BEPs.

Furthermore, the BEPxxx  scheme is used in a variety of technical  systems (like github groups and http redirects), so introducing non-standard characters might also pose technical problems, now or in the future.

**Comment by sappelhoff** [comment]
> I prefer the principle to keep the BEP naming simple

agreed

> I have a doubt about how to name each BEP

before "officially starting" a BEP (i.e., giving it a number, listing it on the website, etc.) I would also kindly ask you to solicit feedback and open a discussion on which BEPs exactly you want to create --> this could best be done in an issue on the specification repository: https://github.com/bids-standard/bids-specification/

**Comment by josator2** [comment]
As far as naming is concerned, I will follow the guidelines indicated. I have also posted a new discussion recommending discussion of the process. 

I look forward to your comments. Best regards.

**Comment by sappelhoff** [comment]
Hi @josator2 I have seen your post, thanks! As for comments, this is not really a domain where I know a lot so I'll hold back with comments a bit. Hopefully other interested people will chime in.

One recommendation to you is to heavily re-format your post to be more specific and easy to read for people: Currently the title and description require users to be familiar with BEP025, which many (most) people are not. That _could_ explain why so far, nobody has replied.

Fingers crossed people will find it and discuss with you about the potential merits :-)

**Comment by sappelhoff** [comment]
I added the following sentence to the BEP025 document:

> NOTE: The contents of this BEP will be split up into smaller proposals to be suggested for inclusion in the BIDS specification.
>
> BEP025 “as is” in the present document  is currently no longer under consideration for inclusion in the BIDS specification.

I further made an archival copy of the Google Doc to be kept with the BIDS maintainers.

I will now move BEP025 from the list of "active BEPs" to a list of "retired BEPs".

We still welcome any sub-packages from the BEP025 that can be split off the overall work package and integrated into the BIDS specification. Such sub-packages may take the form of new, smaller BEPs, but can also be suggested to the BIDS specification directly via a process of GitHub issues and GitHub pull requests that will be reviewed directly be the community and BIDS maintainers.

This has been agreed upon by BIDS maintainers and the BIDS steering group.

Thanks for all your contributions so far!
