### ISSUE TITLE
Update  date of last commit for each converter 

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#248]
Random thought 

- Write python script to ping github api for last commit date of each converter to update yaml file

- add monthly workflow to run script and open pr in case of changes.

**Comment by effigies** [comment]
Could we do something to dynamically retrieve the last tag, instead of making PRs? For example, shields update based on the latest version in places (like packages on pypi). There might be something that includes date as well.

**Comment by Remi-Gau** [comment]
Yup could do. Those some converters are just script so we may be dealing with repos that have no tags or release.
But we can make that flexible indeed.

**Comment by Remi-Gau** [comment]
Could be done use the github API: just require to track the name of the default branch of each repo somewhere

https://api.github.com/repos/cpp-lln-lab/bids-standard/bids-website/gh-pages
