### ISSUE TITLE
Move maintainers doc out of spec wiki / google docs and into the website

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#252]
https://github.com/bids-standard/bids-specification/wiki

- maintainers guide --> should become a page on the bids website (as it's not regularly edited)
- maintainers biweekly meeting notes --> stays a Gdoc, but linked in website (read access)
- ~~maintainers monthly report --> stays a collection of Gdocs, but the folder is linked in the website (read access)~~
    - EDIT 2024-06-01: the monthly maintainers report for the SG will now be that we link SG members to our (well curated) biweekly meeting notes, and ask them to please see the most recent two meetings.

**Comment by sappelhoff** [comment]
could you please elaborate on your suggestion? What are your plans with the meeting notes, guide, and monthly report, respectively?

**Comment by Remi-Gau** [comment]
Mostly have this as a proper webpage on the website and not a page on a github wiki.

The only thing I actually would get out of the drive and into its own page would be this one:

- https://docs.google.com/document/d/11U43QmYVZUVdCxpJeezmYpkHf4sbzWjjN2EIjbk4Pfo/edit

Meeting notes and monthly report would stay on google drive.

**Comment by sappelhoff** [comment]
makes sense to me. Perhaps also a good time to finally consolidate the maintainers guide.
