### ISSUE TITLE
add a non exhaustive list of "what constitue a contribution"

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#257]
Are defined as contributors the people who are listed as contributors on the specification.

But we have started including more people: people who are contributors on non-merged BEP most of them are included in the listing of the spec by now.

We are also slowly including people who contributed to the validator, starter kit...

It would be nice to at least a list of examples of what constitute a contribution. I don't think we can / should a clear absolute rule but some guidelines may help people know if they can claim to be added to our contributors list.

**Comment by sappelhoff** [comment]
I think I would count contributors to BIDS aware software as contributors as well. Some people who develop mne-bids for example have never interacted with bids-standard repositories, but have provided lots of feedback and insight that others (I, for example) have then brought over here.

**Comment by Remi-Gau** [comment]
Yup I agree.

**Comment by CPernet** [comment]
= check the list of authors from the list of tools

**Comment by sappelhoff** [comment]
Once we have clarified this somewhere, we may also link to it from the BIDS governance, where it currently only says:

> Engagement can range from writing copy text in the specification to providing feedback on projects such as the [BIDS starter kit](https://bids-standard.github.io/bids-starter-kit/).

https://bids.neuroimaging.io/governance.html#bids-contributors-group
