### ISSUE TITLE
Please include sim2bids to the converters list

### ISSUE THREAD

**Issue by dissagaliyeva** [bids-standard/bids-website#266]
### Your idea

Hi,

We would like to ask you to include [sim2bids](https://github.com/dissagaliyeva/sim2bids) in the [converters list section](https://bids.neuroimaging.io/benefits). The app was developed following the principles of [BEP034](https://docs.google.com/document/d/1NT1ERdL41oz3NibIFRyVQ2iR8xH-dKY-lRCB4eyVeRo/edit?usp=sharing) which is also referenced in #203. It converts computational data (simulations) to a BIDS-compliant format. 

Here are the specs for an easier integration process:
- Name: sim2bids
- Expected input: network and coordinate files in CSV/TSV/DAT/Numpy arrays/HDF5, zip folders, and code files in MATLAB/Python/R
- Language: Python
- Comment: GUI to easily convert simulation results to BIDS format.

Thanks a lot in advance! Let me know if you have any questions. 

From Prof. Petra Ritter, Dr. Jil Meier, Dr. Michael Schirner, and Dinara Issagaliyeva

**Comment by Remi-Gau** [comment]
Here is a preview of how it would look: 

https://deploy-preview-267--astounding-beignet-8ca2d6.netlify.app/benefits.html#miscellaneous

is that OK with you?

**Comment by dissagaliyeva** [comment]
@Remi-Gau that's perfect! thanks a lot :)
