### ISSUE TITLE
fix dead link

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#283]
FILE: _posts/2022-09-01-NIRS-community-review.md

[✖] https://bids-specification.readthedocs.io/en/bep030/04-modality-specific-files/11-functional-near-infrared-spectroscopy.html

**Comment by sappelhoff** [comment]
closed in https://github.com/bids-standard/bids-website/commit/0638b209cfcda6e59e50f7e414302bbdd7bd94e0
