### ISSUE TITLE
Mention when each BEP was started and/or merged 

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#318]

**Comment by christinerogers** [comment]
Might also useful to indicate: 
- if revisions are in progress (or expected to be published when) 
- last activity in the doc? (Googledocs api might help) 
- recently opened/closed issues

**Comment by Remi-Gau** [comment]
from the coming BIDS paper

BEP001 | Quantitative MRI (qMRI) | 2021-02-23 (v1.5.0)
-- | -- | --
BEP003 | Common Derivatives | 2020-06-11 (v1.4.0)
BEP005 | Arterial Spin Labeling (ASL) | 2021-02-23 (v1.5.0)
BEP006 | Electroencephalography (EEG) | 2019-03-04 (v1.2.0)
BEP007 | Hierarchical Event Descriptor (HED) Tags | 2018-04-19 (v1.1.0)
BEP008 | Magnetoencephalography (MEG) | 2018-04-19 (v1.1.0)
BEP009 | Positron Emission Tomography (PET) | 2021-04-22 (v1.6.0)
BEP010 | intracranial Electroencephalography (iEEG) | 2019-03-04 (v1.2.0)
BEP018 | Genetic information | 2020-04-14 (v1.3.0)
BEP030 | Near Infrared Spectroscopy (NIRS) | 2022-10-29 (v1.8.0)
BEP031 | Microscopy | 2022-02-15 (v1.7.0)

**Comment by Remi-Gau** [comment]
> Might also useful to indicate:
> 
>     * if revisions are in progress (or expected to be published when)

Revisions in the google doc?

>     * last activity in the doc? (Googledocs api might help)

Never played with that API. But it could indeed be a sign of how "alive" the doc is

>     * recently opened/closed issues

Not sure about that one: do we have that many BEP related side issues?

**Comment by Remi-Gau** [comment]
The PR allows to create something like this:


![newplot](https://github.com/bids-standard/bids-website/assets/6961185/4fc857aa-9aeb-4db8-80b1-7860df4c7342)

**Comment by Remi-Gau** [comment]
Note that a "live" browsable version is visible as part of the PR #322

https://deploy-preview-322--astounding-beignet-8ca2d6.netlify.app/bids_timeline.html
