### ISSUE TITLE
Update table of status of all BEP

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#329]
- in the yml that is used to render the tables
- in our internal google spreadsheet

**Comment by sappelhoff** [comment]
> in our internal google spreadsheet

just so that I understand: I assume you mean the doc called "BEP project status" under `BIDS_maintainers/BEPs`?

**Comment by Remi-Gau** [comment]
that's the one, indeed

**Comment by Remi-Gau** [comment]
closing: we should get an automatic reminder for the next updates
