### ISSUE TITLE
Highlighting BIDS Tools : Converters section needs a TOC and/or its own Tools Portal page 

### ISSUE THREAD

**Issue by christinerogers** [bids-standard/bids-website#331]
### Your idea

[ will raise at the next Maintainer's meeting - @Remi-Gau if you're already on this, consider this an upvote of support]
Looking at the Converters section of the Benefits page: 
- It's grown so long now it needs an index (links to jump to MRI vs. EEG vs Physio converters)
- Could perhaps be better named Tools since a lot of these do more than convert (e.g. anonymize, validate, package)
- possibly hiding its light under a bushel in the Benefits page.  
- 
To which end:
- a Tools Portal webpage could be a better home -- parallel to @Remi-Gau 's in-progress Bids-examples Datasets Portal page 

Plus, looking at OHBM + Hackathon it strikes me that the BIDS tools and converters are: 
- close to duplicating efforts because people don't know what's out there, in development or not. This isn't the fault of the page or maybe even the current process but a first step to take would be to give the current list all the publicity/prominence it can get, and add more/searchable detail as a next step.
- The tools and converters are also the sine qua non of BIDS adoption and growth, and a powerful demonstration of community engagement which would be good to highlight.

**Comment by christinerogers** [comment]
Yarik feels similarly: [starterKit#306](https://github.com/bids-standard/bids-starter-kit/issues/306)
Seems like there's consensus (per maintainers meeting Aug.10) for:
- Converter page should moved somewhere else as Tools
- A way to organize/link/index in one place (mkdocs) like the datasets page
-[ ] first step is to take tools listed in bids website repo and Yaml it.

Start a new process for adding new tools: 
-[ ] get a workflow template/issue form to help with this (streamlining/automating Contributors, tools, not necessarily data submissions)
- would be nice to have a way to invite people to list a tool in progress

**Comment by Remi-Gau** [comment]
FYI
For the moment things are being centralized in the awesome bids repo:

https://github.com/bids-standard/awesome-bids#converters

**Comment by Remi-Gau** [comment]
given that the converters have now their own section I feel that this can be closed.

@christinerogers reopen if you feel otherwise or extract the bits that have not been adressed in another issue.
