### ISSUE TITLE
Contributors RTD  page - add link to 'how to add"

### ISSUE THREAD

**Issue by christinerogers** [bids-standard/bids-website#333]
### Describe your problem in detail.

Tho this is pretty chicken-and-egg --  the [RTD Contributors page](https://bids-specification.readthedocs.io/en/stable/appendices/contributors.html) should show a link "How to suggest/add a missing contributor name" -- because it's the most public version of the page. 
cc @Remi-Gau thoughts on the easiest way to do this?

**Comment by Remi-Gau** [comment]
I think this relates to our contrib workflow PR: https://github.com/bids-standard/bids-specification/pulls
