### ISSUE TITLE
Governance document: Small amendments

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-website#349]
This part seems like it should be amended in several ways:

https://github.com/bids-standard/bids-website/blob/c4c62f2cb2dcddd07a20b8c203fd11db50f084b6/_pages/governance.md?plain=1#L249-L255

1. Twitter is now called X
2. We have Mastodon and Bluesky channels

This should perhaps also be reflected here:

https://github.com/bids-standard/bids-website/blob/c4c62f2cb2dcddd07a20b8c203fd11db50f084b6/_pages/governance.md?plain=1#L212-L215

Thoughts?

**Comment by Remi-Gau** [comment]
Tempted to replace that by "our social media channels" and point to a place where they are listed.

I don't really feel like "amending the BIDS constitution" every time some egotistical megalomaniac decides to take over a social network. 😉
