### ISSUE TITLE
Add mercure to the list of 'other tools' on software page

### ISSUE THREAD

**Issue by jmsocallaghan** [bids-standard/bids-website#360]
We have recently developed an open-source module for dcm2bids conversion (https://github.com/mercure-imaging/mercure-dcm2bids) for use with our open-source mercure DICOM orchestration software ( https://mercure-imaging.org/). I have provided a  description below:

•	[mercure](https://mercure-imaging.org/):
An open-source DICOM orchestration platform that can integrate containerized apps into the clinical workflow. The [mercure-dcm2bids](https://github.com/mercure-imaging/mercure-dcm2bids) app can be used to perform BIDS conversion of DICOM studies sent to mercure directly from a scanner or PACS.

**Comment by sappelhoff** [comment]
Thanks @jmsocallaghan please have a look at this page: https://github.com/bids-standard/bids-website/blob/a4dbd49ad69c54455e5090099bbb6ef6fcf47557/_data/converters.yml#L21

and feel free to open a pull request to add your software to the website. We'll review it and then merge the PR to make this happen.

**Comment by jmsocallaghan** [comment]
Thanks @sappelhoff I just created PR #362.

**Comment by Remi-Gau** [comment]
Thanks @jmsocallaghan
