### ISSUE TITLE
Add Christine photo to Governance page, as 2022+ maintainer

### ISSUE THREAD

**Issue by christinerogers** [bids-standard/bids-website#371]
Hi @Remi-Gau,  Could you advise so I can complete this? 

I'd like to add [my headshot](https://drive.google.com/file/d/1m5XhFUEm_cHjkMUJmJCqG_2PKjLqUBuN/view?usp=sharing) on the Governance page [BIDS Maintainers Table](https://github.com/bids-standard/bids-website/blob/gh-pages/_pages/governance.md#bids-maintainers-group), the way Nell's appears. 
Thanks - I've looked through the code and PRs a little, just not sure how to get the image to appear in [members_table.html](https://github.com/bids-standard/bids-website/blob/gh-pages/_includes/members_table.html) etc.

p.s. I've also added this step [as a to-do for each new maintainer](https://github.com/bids-standard/bids-website/issues/371) to do while on-boarding - does that work for future ppl?

**Comment by Remi-Gau** [comment]
We simply grab the picture from your github account, so if you add a picture there the website will be updated with this.

**Comment by christinerogers** [comment]
Ah, sorry, i'm never going to add a photo on my github account (too public), but I would really like to add a photo on the Maintainers page.  can we find a way?

**Comment by Remi-Gau** [comment]
So either we use another url for the image a maintainer wants to use or we add the image to the repo.

Either way this will require modifying
- this yml file: https://github.com/bids-standard/bids-website/blob/gh-pages/_data/maintainers.yml

```yml
    - name: "Christine Rogers"
      git: "christinerogers"
      picture: ADD_URL_HERE
```

- this template file to read from the picture if it is provided: https://github.com/bids-standard/bids-website/blob/434cfeef23f63522cec2b1ea8d97ceb091546e15/_includes/members_table.html#L15

**Comment by christinerogers** [comment]
no problem, let's use this URL https://github.com/christinerogers/bio/blob/main/headshot_crogers_202010.jpg
