### ISSUE TITLE
add a section or page for "non BEP related working groups"

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#383]
The governance allows other working groups that are not BEP related.

https://bids.neuroimaging.io/governance.html#other-workinginterest-groups

For transparency and ease of access for people who main want to join them, we should have a space for them in the website.

Like for BEP this should include active and "resolved" working groups.

One thing that we can "retroactively" call a working group that we have had so far is the one that was suggesting amendments to the governance last fall.

https://docs.google.com/document/d/18PpfSgcHckqejTZsRZlEDlJ_yD3JiwSQ8kCjVXorg6U/edit

We should also list the "online presence working group".

**Comment by christinerogers** [comment]
This could be an easy warm-up `gsod` task if you don't have time to create more granular issues, @Remi-Gau

**Comment by Remi-Gau** [comment]
Will take of this one.

Other things to do:

- set up templates google doc, or markdown doc to initiate a new working group
