### ISSUE TITLE
update Get Involved page and make BEP dashboard more prominent / colourful

### ISSUE THREAD

**Issue by christinerogers** [bids-standard/bids-website#384]
for 2024, possibly GSOD -- based on Maintainers discussion April 18
https://bids.neuroimaging.io/get_involved#extending-the-bids-specification

@ericearl @Remi-Gau could be great place for DVD to get started with minor but impactful top-level website content updates/improvements.  

Can be done before OHBM: 
~* update Get Involved page with a link to form for feedback (this was one of the first deliverables for GSOD)~
~* convert the paragraph of options (ways to get involved) to bullets to make it more readable / punchy~
* make the BEP dashboard more prominent -- it could and probably should be on its own page (people do look for BEP status, more than they look how to get involved)
* add colour status when ready

Around OHBM: 
* update BEP status table  
* add link to best practices Franco's OHBM 5 best-practice slides

**Comment by christinerogers** [comment]
Note these updates are in progress and content is being split across : 
* https://bids-website.readthedocs.io/en/latest/bep/
* https://bids-website.readthedocs.io/en/latest/collaboration/governance/

**Comment by Remi-Gau** [comment]
Current WIP page for this: https://bids-website.readthedocs.io/en/latest/bep/beps.html

Suggestions are welcome to make this more colorful and prominent.

**Comment by iamdamion** [comment]
PR #412 addresses point 2 of Can be done before OHBM.

**Comment by iamdamion** [comment]
Edited and am moving the BEP dashboard items to a new issue.
