### ISSUE TITLE
fix broken links

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#385]
this ci report points out a few broken links on the website.   If these can be identified and corrected, great. 

https://github.com/bids-standard/bids-website/actions/runs/8700915053/job/23861938919#step:4:517

**Comment by effigies** [comment]
Looks like a rename without a redirect: https://www.internationalbraininitiative.org/data-standards-and-sharing-working-group -> https://www.internationalbraininitiative.org/data-standards-and-sharing
