### ISSUE TITLE
fix links for BEPS

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#386]
On this page: https://bids.neuroimaging.io/get_involved.html

Completed BEPs should link to a page in the spec or to whatever website hosts the final version of that BEP.

Also check that the link to each BEP points the relevant PR if the BEP has left the google doc stage.

**Comment by Remi-Gau** [comment]
probably a better way to keep track of this would be to add the relevant link in the yaml files for the different BEPS: 

https://github.com/bids-standard/bids-website/tree/gh-pages/_data

**Comment by MeenuyD** [comment]
Hello, @Remi-Gau I am interested in participating in GSOD can you please share some community links like Slack or anything else and what is the process?

**Comment by christinerogers** [comment]
Hi @MeenuyD - Please note [as of April 15 this Google Season of Docs project is fully staffed](https://neurostars.org/t/call-for-applications-for-google-season-of-docs-2024-filled/28760/3?u=crogers) and we unfortunately can't invite further applicants.
Thank you for your interest in our GSOD project and contributions to the [BIDS initiative](https://bids.neuroimaging.io/), we are always looking to welcome new members to our open-source community.  

on behalf of the BIDS GSOD mentors

**Comment by christinerogers** [comment]
@Remi-Gau can this go next?  Can i move it to to-do / next project board column ?

**Comment by Remi-Gau** [comment]
Yes I would say this is high priority.
