### ISSUE TITLE
Consider giscus for comments

### ISSUE THREAD

**Issue by ericearl** [bids-standard/bids-website#392]
### Your idea

This is a possible commenting system for passer-bys or involved users alike:

https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

**Comment by christinerogers** [comment]
@bendhouseart is this for the maintainers meeting or for `dvd` ?

**Comment by ericearl** [comment]
@bendhouseart implemented Giscus at this point. Are we really still considering it? Should we close this issue?

**Comment by bendhouseart** [comment]
Yes!
