### ISSUE TITLE
Redirect question about BEP in the FAQ towards the BEP page

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#402]
[This answer](https://bids-website.readthedocs.io/en/latest/faq/faq_general.html#is-your-data-type-not-covered-in-the-current-bids-specification) should not list all the beps but instead redirect to [the BEP table](https://bids-website.readthedocs.io/en/latest/bep/beps.html).

**Comment by iamdamion** [comment]
This is finished in [PR #410](https://github.com/bids-standard/bids-website/pull/410), but also appears to have some lingering file changes from [PR #399](https://github.com/bids-standard/bids-website/pull/399) included that were already approved and merged. 

Not sure if we should clean up PR #410 for clarity so it only includes the redirect question fix.

**Comment by bendhouseart** [comment]
Closed with pr #410
