### ISSUE TITLE
Newcomer flow

### ISSUE THREAD

**Issue by patrick-g-h** [bids-standard/bids-website#418]
With the constantly growing number of resources about BIDS, I thought it would be useful to organise the "flow" that we expect newcomers to follow -- starting from Googling "what is BIDS" to finding their answer.

This is just a rough skeleton so far, but happy to hear any input related to this!

![image](https://user-images.githubusercontent.com/12662110/43373441-98003cc2-9377-11e8-85c5-aea3f533bc0c.png)

**Comment by Remi-Gau** [comment]
OK I think this is now become obsolete or a new flow within the website should be reimagined.
