### ISSUE TITLE
BEP dashboard updates

### ISSUE THREAD

**Issue by iamdamion** [bids-standard/bids-website#435]
make the BEP dashboard more prominent -- it could and probably should be on its own page (people do look for BEP status, more than they look how to get involved)
add colour status when ready
Around OHBM:

update BEP status table
add link to best practices Franco's OHBM 5 best-practice slides

NOTE: pulled from #384

**Comment by Remi-Gau** [comment]
best practices points are (from: https://osf.io/5pz7c)

- Lack of clear timeline for people to respond to proposals 
- Lack of clear timeline for triage of comments on proposals
- Non-standardized procedure for commenting (e.g., some comments 
are too short, others too long)
- No procedure for conflict resolution. 
- Not an explicit role of BEP leads to decide / triage options

**Comment by Remi-Gau** [comment]
not exactly sure how this relates to the issue

**Comment by christinerogers** [comment]
thanks remi for linking in those notes from the OHBM2024 BIDS Townhall in Seoul Korea, that's super helpful for the next step of dashboard planning

**Comment by Remi-Gau** [comment]
Will consider this one done for now.
Let's open another issue with more suggestions for improvement if there are.
