### ISSUE TITLE
centralize all converters in a single yml file to avoid duplicates

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#442]
we should have only a single yml file that lists ALL converters and render different tables based on their datatypes, because currently we have duplicates of some converters (BIDSme is another one)

_Originally posted by @Remi-Gau in https://github.com/bids-standard/bids-website/issues/441#issuecomment-2189004528_

Tasks:
- centralize info about all converters in one file
  - resolve any conflicts or inconsistencies in case of duplicate
- adapt mkdocs [macros](https://github.com/bids-standard/bids-website/blob/a7260c1880f8d9b63b5a2bd1b8303221ccf6bf11/macros/macros.py#L25) and its jinja template to render all tables in by filter on the datatypes

**Comment by Remi-Gau** [comment]
@iamdamion pinging you on this one in case you got time.

**Comment by christinerogers** [comment]
status: in progress, no blockers
