### ISSUE TITLE
The landing page of the tool section should have brief description of the different sub sections when can find in it.

### ISSUE THREAD

**Issue by bendhouseart** [bids-standard/bids-website#447]
The landing page of the tool section should have brief description of the different sub sections when can find in it.

Very confusing for people on mobile who otherwise have to open the navbar to discover the content.

_Originally posted by @Remi-Gau in https://github.com/bids-standard/bids-website/discussions/407#discussioncomment-9911851_

**Comment by christinerogers** [comment]
#458 is the PR addressing this.

**Comment by Remi-Gau** [comment]
closing as duplicate
