### ISSUE TITLE
Add bids2table to list of tools

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#448]
unless I am mistaken we do have it in our list of tools

https://github.com/childmindresearch/bids2table

**Comment by effigies** [comment]
Was thinking we should add it to awesome bids, too.

**Comment by Remi-Gau** [comment]
awesome bids reads from the bids website metadata, so can update it here and then update the submodule in awesome bids.

actually probably should do this now so that awesome BIDS tracks the "new" main branch of the website
