### ISSUE TITLE
Improve Impact Page

### ISSUE THREAD

**Issue by bendhouseart** [bids-standard/bids-website#481]
Reorganize the impact page:

- [ ] Reorder content to show metrics, history, deliverables, and place how to cite etc etc at the very end/bottom of page
- [ ] Integrate slides from OHBM into impact page, no reason not to use existing work.
- [ ] Add/update paragraphs/statements for existing content? @iamdamion @ericearl  update this item.

**Comment by Remi-Gau** [comment]
closed in favor of #486
