### ISSUE TITLE
Evaluate the navigation before October 1st

### ISSUE THREAD

**Issue by ericearl** [bids-standard/bids-website#482]
Navigation should be inspected per top tab for completeness, cohesion, and ease of use without using the search functionality. Reviews can either be conducted in a post to this issue, or as a PR for further review. @iamdamion Should receive and respond to the (at least 2) mentor reviews.

**Comment by bendhouseart** [comment]
- About -> left navigation pane is empty
- Datasets -> The left navigation pane is a bit empty, but it's fully functional
- Impact -> left navigation pane is empty, but again that isn't a navigation issue just a note.
- Merch -> is great no notes

Okay all the navigation took me to where I expected it. I think uniformity is overrated with respect to how each page appears.

**Comment by christinerogers** [comment]
Remi and Anthony's evaluation :  this is resolved nicely.
Followups are already documented with issues elsewhere or will be opened / cross-linked by @Remi-Gau

**Comment by Remi-Gau** [comment]
potential follow up or more precise issues to help improve navigation:

- https://github.com/bids-standard/bids-website/issues/525
- https://github.com/bids-standard/bids-website/issues/356
- https://github.com/bids-standard/bids-website/issues/359
- https://github.com/bids-standard/bids-website/issues/452
- https://github.com/bids-standard/bids-website/issues/471
- https://github.com/bids-standard/bids-website/issues/511
- https://github.com/bids-standard/bids-website/issues/518
