### ISSUE TITLE
Add a Contact Us page with an embedded CryptPad survey

### ISSUE THREAD

**Issue by ericearl** [bids-standard/bids-website#484]
### Your idea

Add a simple “Contact Us” page for gathering questions/feedback if people don’t want to contact BIDS some other way. This requires:

- [ ] Content for the description of the sorts of things (basically anything about BIDS anywhere) that could be entered into the contact us form
- [ ] A (very short) CryptPad survey with a "name" short text field, an "email" short text field (see if it can be validated), and an open text "BIDS question or comment" field

**Comment by Remi-Gau** [comment]
Unless we hear about someone says this is not enough I would say : no.

**Comment by ericearl** [comment]
Done!
