### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by pgleeson** [bids-standard/bids-website#50]
At the bottom of https://bids.neuroimaging.io/ the link to the INCF is incorrect. Also the link on the INCF site for the task force has been moved/removed.

The Feedback link at the top of the page sends you to the bottom of the page but there's nothing there about giving feedback...

**Comment by sappelhoff** [comment]
Thanks for the report @pgleeson I can confirm the three issues.

@franklin-feingold do you know what kind of "Feedback form" we used to have?

regarding the links, this should be an easy fix that I will submit

**Comment by franklin-feingold** [comment]
AFAIK we didn't have an official feedback form. I created a [quick form](https://forms.gle/pPU6dwhqUvY8SAZ47) to capture feedback

Thank you for raising this @pgleeson !

**Comment by sappelhoff** [comment]
> AFAIK we didn't have an official feedback form. I created a quick form to capture feedback

cool, we just need to make sure that we get notifications upon new entries into the form :+1: Can you take care of that?
