### ISSUE TITLE
Go Through Second Round of Feedback w/ Mentors and Working Group

### ISSUE THREAD

**Issue by bendhouseart** [bids-standard/bids-website#500]

**Comment by christinerogers** [comment]
there was some feedback, not much 
@iamdamion says this is on track for the end date 25 oct

**Comment by christinerogers** [comment]
from check-in Oct. 31 :

@iamdamion has started a googledoc to collage these and is doing a first-pass triage for Nov. 7.  
- [ ] highlight in the doc what's are `easily actionable` and `important/priority` as best you can, colour flag (or use emojis) in the doc  
You can also flesh out triage with `medium size/actionable` `medium priority`, `low`, etc.   Focus on what seems important/priority/relevant/impactful. 

- [ ] Then mentors can take a look and re-triage,  starting Nov.7.   Issues can be created from there. 

- [ ] @bendhouseart is going to do an other email blast Monday Nov. 4 or Tues. Nov.5

- [ ] Then (nov.7 or 10)  @iamdamion can integrate add new responses to the googledoc, do another first-pass triage -- to be coordinated with the mentor triage too Nov.7.

**Comment by bendhouseart** [comment]
Original comments/responses from survey and feedback have been integrated, this issue should have been updated and closed some time ago.
