### ISSUE TITLE
remove DICM2NII from list of BIDS converters

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-website#519]
Maybe we can mention it is used by most BIDS converters but I do not think it counts as a BIDS converters.

https://bids-website.readthedocs.io/en/latest/tools/converters/others.html#miscellaneous

**Comment by Remi-Gau** [comment]
closed by #531

**Comment by yarikoptic** [comment]
I think we might want to double check with @neurolabusc since IIRC Chris was working on also providing facility to name files according to BIDS, but not sure if "all the way" (folders) and providing top level `dataset_description.json` etc.

**Comment by neurolabusc** [comment]
[dicm2ni](https://github.com/xiangruili/dicm2nii) is a Matlab tool that creates NIfTI images and BIDS sidecars. It is developed by @xiangruili, and is independent from dcm2niix that I maintain (which is C code that can be compiled as a command line executable or [as webseembly](https://niivue.github.io/niivue-dcm2niix/) that also creates NIfTI images and BIDS sidecars. I see both of these tools as the core components to wrappers that create BIDS compatible datasets. The core tools do the explicit mapping between DICOM and BIDS, while the wrappers handle the implicit aspects such as providing the intention. For example heudiconv, dcm2bids, ezBIDS and pet2bids are all dcm2niix wrappers. 

It is true that the imminent release of dcm2niix inserts a [BidsGuess](https://github.com/rordenlab/dcm2niix/tree/development/BidsGuess) field into the BIDS sidecar that can provide a strong hint for wrappers. In a few cases, this might be sufficient to provide a full structure for the data. However, I do think there will still be a need for wrappers, often using these hints to detect edge cases where the configuration files may be erroneous. 

Therefore, I would not include dcm2niix  in this list of [BIDS converters](https://bids-website.readthedocs.io/en/latest/tools/converters.html), rather it is a core dependency for almost all of these wrappers.

However, I am less familiar with dicm2nii, and I am not sure how sophisticated the [BIDS formatting is](https://github.com/xiangruili/dicm2nii/blob/1b7b574ae18b9e024bfd11af08bb8f9c5d31e637/dicm2nii.m#L20).

**Comment by yarikoptic** [comment]
thank you @neurolabusc , and sorry for my bad vision -- I see d..2nii and think of you ;)

**Comment by Remi-Gau** [comment]
I am happy to mention those tools somewhere else  if someone feels strongly about it but probably not under "BIDS converters"
