### ISSUE TITLE
Improve website contributor workflow

### ISSUE THREAD

**Issue by asmacdo** [bids-standard/bids-website#529]
I've created a PR for the Bids-app section
https://bids-website.readthedocs.io/en/latest/getting_started/bids_apps/tutorial.html

FWIW I found it a bit tricky to make that contribution due to a couple oddities:

"Go to repository button" took me to the `gh-pages` branch, which did not contain the content that I wanted to edit. (I needed the `main` branch.)
![Image](https://github.com/user-attachments/assets/3f5fa10b-4605-4850-af27-a26d8e6616b1)

`gh-pages` branch (being the default) has a CONTRIBUTING.md and a README, one of them should explain the `main` branch, and maybe point to the contributor docs for that branch as well, since deployment instructions are totally different. (I erroneously attempted to install jekyll rather than mkdocs)

I'd be happy to contribute if someone can give me guidance :)

**Comment by Remi-Gau** [comment]
In general things have been set up so simple changes can be done via the edit button.

![Image](https://github.com/user-attachments/assets/08fa6701-85c4-4fde-b503-c203c43c25c1)

But you are correct let me try to improve things as they show up on the gh-pages to redirect to the main one.

**Comment by Remi-Gau** [comment]
OK the README and the CONTRIBUTING on the gh-pages now point to the main branch.

And the link to the repo in the website should send you to the main branch.

Added a CONTRIBUTING to the main branch.

Still want to improve the README on main a little bit.

**Comment by Remi-Gau** [comment]
will close this for now but @asmacdo reopen if you think this is not fixed.
