### ISSUE TITLE
Request for feedback: Reorganizing the bids website

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-website#55]
The Steering Group has requested for community feedback an idea to organize the [bids website](https://bids.neuroimaging.io/). The proposal and conversation can be found on [NeuroStars](https://neurostars.org/t/request-for-feedback-reorganizing-bids-website/5476)

**Comment by robertoostenveld** [comment]
We received feedback from various people. After [my clarification](https://neurostars.org/t/request-for-feedback-reorganizing-bids-website/5476/5?u=robert) that the goal is not to reorganize for the aesthetics of single- versus multiple-pages, but rather to improve the structure and add additional documentation, I believe that consensus is that a new website organization is preferred.

I had a go at it and implemented a new website, copying the original content and - where possible - the original format. I will send a pull request shortly...

**Comment by robertoostenveld** [comment]
I have implemented the new website via #56. Thanks for the feedback so far, let's keep working on this together to make it even better.
