### ISSUE TITLE
[BUG] Dataset is under wrong category on datasets page.

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-website#552]
### Describe your problem in detail.

This request refers to page: [https://bids-website.readthedocs.io/en/latest/datasets/index.html](https://bids-website.readthedocs.io/en/latest/datasets/index.html).

The dataset  `eeg_ds003645s_hed_demo` is currently listed in the **Microscopy** category, but it doesn't have any meaningful microscopy data.

### Describe what you expected.

Could we please have a category called HED --- as this dataset demonstrates the use of HED across a bids dataset including annotation of files such as `participants.tsv`?

**Comment by Remi-Gau** [comment]
good catch: I have a PR in progress to better organize the listing from the BIDS example will add this fix + feature in and will ping you for a review.

**Comment by Remi-Gau** [comment]
The eeg_ds003645s_hed_demo dataset does contain what appears to be microscopy and motion data so it will in any case also appear in those 2 categories: 
https://github.com/bids-standard/bids-examples/tree/master/eeg_ds003645s_hed_demo/sub-004/ses-1/micr

https://github.com/bids-standard/bids-examples/tree/master/eeg_ds003645s_hed_demo/sub-004/ses-2/motion

**Comment by Remi-Gau** [comment]
- PR #507 fixes this:

see https://bids-website--507.org.readthedocs.build/en/507/datasets/examples.html#hed
