### ISSUE TITLE
disable the wiki

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-website#58]
I propose that we disable the [wiki](https://github.com/bids-standard/bids-website/wiki) for this repository. Do you agree @dorahermes ?

**Comment by dorahermes** [comment]
+1 we want to avoid confusion with the bids-starter-kit

**Comment by robertoostenveld** [comment]
@sappelhoff could you disable the wiki on the bids-website?

**Comment by sappelhoff** [comment]
done. Thanks for spotting this.
