### ISSUE TITLE
BIDS steering email

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/bids-website#583]
### Your idea

Hi everyone!

We now have an email for the BIDS steering (bids.steering@gmail.com) and we would like to mention it on the BIDS website (similarly to what is done for the BIDS maintenance email). 

As the BIDS website is currently being revamped, shall I try and add this now or shall we ponder until the update is done? 

Thanks!

**Comment by ericearl** [comment]
@cmaumet Feel free to add it here as a PR! And let us know if you want/need any kind of help or feedback doing that.

https://github.com/bids-standard/bids-website/blob/main/docs/contact/index.md

**Comment by Remi-Gau** [comment]
closed by #584
