### ISSUE TITLE
Special Projects page to mention GSOC/GSOD projects etc 

### ISSUE THREAD

**Issue by christinerogers** [bids-standard/bids-website#592]
per chat with @Remi-Gau  would be lovely to : 
- [ ] create a new page for Special Projects. 

- [ ] current BIDS GSOD project for website improvement should be listed & linked there  (link to the Case Study) 

also list & link: 
- [ ] [2018 report on INCF-supported GSOC project to do the BIDS starter kit ](https://github.com/bids-standard/bids-starter-kit/blob/main/reports/Google-2018-report.md)
- [ ] since the starter kit has been moved, link to where its traces are now 

not not related: 
- [ ] within that [2018 GSOC Starter Kit page](https://github.com/bids-standard/bids-starter-kit/blob/main/reports/Google-2018-report.md) would be ideal to add somewhere a tiny credit that it was facilitated/supported by INCF.

**Comment by Remi-Gau** [comment]
will consider this one done
