### ISSUE TITLE
the logo should be added to the website header

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-website#61]
as mentioned by @yarikoptic in https://github.com/bids-standard/bids-website/pull/56#issuecomment-565739808 and by @sappelhoff

**Comment by christinerogers** [comment]
potential first `gsod` issue if @ericearl @sappelhoff @Remi-Gau agree - relevant, simple, self-explanatory ?

**Comment by Remi-Gau** [comment]
FYI This only makes sense if we do not completely fuse all our websites in one. 😜

**Comment by Remi-Gau** [comment]
closing as this is now obsolete
