### ISSUE TITLE
the link to the specification can be made more direct

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-website#64]
Right now the menu item links to a page that subsequently links to the specification.

This was suggested by @CPernet in https://github.com/bids-standard/bids-website/pull/56#issuecomment-566587448 and later also by @jbteves. 

However, @adelavega argued against it in https://github.com/bids-standard/bids-website/pull/56#issuecomment-567166302.

**Comment by sappelhoff** [comment]
This can be done easily using `jekyll-redirect-from` as done in https://github.com/bids-standard/bids-website/pull/104

however, I don't find it too bad to have an intermediate site. And the comment by Alejandro is valid:

> Having an external link in the main nav is not ideal because it can catch users off guard (unless it has an icon to indicate its an external link). An alternative would be to have more info on the Specification page, so that it serves another purpose and doesn't feel too empty.

**Comment by sappelhoff** [comment]
We are now using the intermediate landing page to separately link to the html and pdf versions of the specification, combined with Alejandro's remark I consider that reason enough to close this issue for now. Feel free to re-open.
