### ISSUE TITLE
post news item about steering group

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-website#65]
As discussed in the steering group, we want to post a news item that introduces us. @KirstieJane has been working on a draft.

I will do some work on the technical side to allow news items to appear with a time-stamp, in reverse chronological order, with an author, with an excerpt and a link to a full page, etc.

**Comment by robertoostenveld** [comment]
@KirstieJane I have added a news section, please see https://bids.neuroimaging.io/news.html and the `_posts` directory within the repository. You should be able to fork the repository,  enable github pages on your own fork, and preview it prior to sending a PR to https://github.com/bids-standard/bids-website. 

If you want or if your own preview does not work, you can also send me a PR and I can preview it on my localhost and on my GH repository.

**Comment by KirstieJane** [comment]
Done in #69
