### ISSUE TITLE
add a FAQ, split for people from different backgrounds

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-website#67]
This was suggested by @choldgraf in https://twitter.com/choldgraf/status/1198737801107271680

**Comment by Remi-Gau** [comment]
so far the FAQ will at least include sections by modality or interest (for example bids apps)

https://bids-website.readthedocs.io/en/latest/

**Comment by Remi-Gau** [comment]
I will close this for now but we may reopen if we get feedback in that direction for the new website
