### ISSUE TITLE
Make it easier to link to subsections on pages

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bids-website#73]
At the moment, we _can_ link to specific news items by adding the heading in lower case (and with `-` instead of spaces) but it isn't easy to get that link itself.

For example:
* https://bids.neuroimaging.io/news.html#meet-the-bids-steering-group
* https://bids.neuroimaging.io/news.html#new-website
* https://bids.neuroimaging.io/news.html#bids-steering-group-election-and-governance-results

Does anyone know of any css etc that can make it easy to get the link - for example by hovering over the heading itself?

**Comment by KirstieJane** [comment]
Duplicate with #72. Closing :)

**Comment by robertoostenveld** [comment]
I hope someone can help to make it easier to link to subsections (i.e. subheadings) on pages. This does not only apply to news items, but for example also to https://bids.neuroimaging.io/benefits.html#other-tools

**Comment by robertoostenveld** [comment]
This technically already works, using https://gist.github.com/asabaylus/3071099 and https://stackoverflow.com/questions/43627485/jekyll-link-within-page, but the links are hard to find if you don't know this. For non HTML developers (e.g. visitors to the website) it will be impossible to find the links to the sections.

**Comment by sappelhoff** [comment]
closed through #79
