### ISSUE TITLE
the list of BEPs should be updated to reflect the open/closed state 

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-website#80]
Going over all BEPs, I noticed in some of them (i.e. in the google docs) that they have been merged with another BEP (mainly with BEP003) and therefore not active any more. 

Once #77 is merged, I propose we update the list of BEPs and move the ones that are not actively being worked on to the bottom of the list (along with MEG, EEG, etc)

**Comment by sappelhoff** [comment]
note that I had taken a stab at this in https://github.com/bids-standard/bids-specification/pull/240

I don't remember from the top of my head why this was reverted later on. I'll have to check.

**Comment by robertoostenveld** [comment]
That was done [here](https://github.com/bids-standard/bids-specification/commit/38224ec3e0b90e6621857a0560956cc76b4d3099#diff-07d4f93564e8c528cc6bd6c59eadea4c) for BEP012,013 and 016 by @franklin-feingold. Perhaps he can comment on this?

I see [here](https://github.com/bids-standard/bids-specification/commits/master/src/06-extensions.md) also that BEP018 (Genetics) has been moved down and later up again. That is still being worked on in this [PR](https://github.com/bids-standard/bids-specification/pull/287), so it should remain in the main list for now.

**Comment by franklin-feingold** [comment]
For BEP012,013, and 016 those are the MR (anat, func, dwi) derivatives - we had combined them into one (BEP003) but then later reverted back to separating out in the effort to make the extensions more "bite-size". Agree - BEP018 should stay on the list

I am preparing to update the BEP status as I've heard back from BEP leads

**Comment by robertoostenveld** [comment]
@franklin-feingold has this been resolved (for now)?

**Comment by franklin-feingold** [comment]
I think so with https://github.com/bids-standard/bids-website/pull/88 being merged in - closing this
