### ISSUE TITLE
Adding style guiding

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-website#82]
related to enabling circle CI on this repo (https://github.com/bids-standard/bids-website/issues/81) we can think about adding [consistent styling](https://github.com/bids-standard/bids-specification/blob/master/.remarkrc) similar to what we enforce in the bids specification repository. 

similar to the specification this will ensure consistency within (and across) our repositories

**Comment by sappelhoff** [comment]
I think that's a good idea, because it can help us to catch syntax mistakes which could result in a bad rendering of the website.
