### ISSUE TITLE
add resolvable identifiers for BEPs

### ISSUE THREAD

**Issue by poldrack** [bids-standard/bids-website#96]
it would be useful if there was a way to resolve individual BEPs to their appropriate page (be it on google docs or wherever).  e.g.:

https://bids.neuroimaging.io/BEP003 which would resolve to `<google doc>`

I'm not sure if github pages has a way to do this but it would be nice to have a more permanent identifier for each BEP.

**Comment by sappelhoff** [comment]
indeed, that would be very useful. This jekyll plugin might be able to do the job: https://github.com/jekyll/jekyll-redirect-from#redirect-to

see this stackoverflow answer: https://stackoverflow.com/a/39735194/5201771

> That plugin does allow for redirecting to external URLs. To redirect your example URL, create a file called tmwtga.html and add the following front matter:
```
---
permalink: /tmwtga
redirect_to:
  - http://www.example.com
---
```
