### ISSUE TITLE
Top-level header for extensions

### ISSUE THREAD

**Issue by poldrack** [bids-standard/bids-website#97]
right now, if one navigates to the site it is not obvious where the extensions are found.  I propose adding a top-level heading for extensions, separate from the "getting involved" page.

**Comment by sappelhoff** [comment]
When we all agree that we should get a separate page (+ top level header) for the extensions, we can think about re-structuring the extensions table in general.

#104 is providing a "jekyll collection" of BEPs.

Making use of such a collection, we could make the separate "extensions page" very simple along these lines:

```
<ul>
  {% for bepin site.bep_collection %}
    <li>
      <a href="{{ bep.url }}">{{ bep.title }}</a>
      - {{ bep.headline }}
    </li>
  {% endfor %}
</ul>
```

**Comment by robertoostenveld** [comment]
I find the number of top-level menu items now already larger than desired; hence I would prefer to switch to a hierarchical menu structure, where the different ways of getting involved are separate pages, each accessible through sub-menu items.

**Comment by Remi-Gau** [comment]
The new website will probably include something for extensions

https://bids-website.readthedocs.io/en/latest/

**Comment by Remi-Gau** [comment]
closing as this seems to now be resolved: in my opinion

reopen if you think otherwise
