### ISSUE TITLE
use target=”_blank” for links to offsite pages (such as extension docs)

### ISSUE THREAD

**Issue by poldrack** [bids-standard/bids-website#98]
For links that point to an offsite page (such as BIDS extension proposals on Google Docs), it would be nice for these to open into a new tab using target=”_blank”.  otherwise the reader loses the context for the new page.

**Comment by sappelhoff** [comment]
This is a good point. Adding a `target=_blank` to markdown may not be easily possible, but there is a jekyll extension that might be just what we need: https://keith-mifsud.me/projects/jekyll-target-blank

> By default all anchor tags and markdown links pointing to an external host, other than the one listed as the url in Jekyll's _config.yml will automatically be opened in a new browser tab once the site is generated.

**Comment by nicholst** [comment]
I thought it was always permissible in Markdown to insert raw HTML, no?  So
we'd just need to replace [text](link) with <a href="link"
target="_blank">text</a> no?

**Comment by sappelhoff** [comment]
> I thought it was always permissible in Markdown to insert raw HTML, no?

yes, that's true.

> So we'd just need to replace

I see now that my sentence about "may not be easily possible" can be easily misunderstood :-)

I was just looking for easy solutions that don't require going through all links manually.

**Comment by sappelhoff** [comment]
[jekyll-target-blank](https://keith-mifsud.me/projects/jekyll-target-blank) is not supported for the gh-pages jekyll builds (see supported "gems" here: https://pages.github.com /versions/)

I'll prepare a PR replacing our current link syntax with `[text](url){:target='_blank'}` for links that point to external sites.
